-- Seed initial data for ACREE CMS

-- Seed Admin User (username: admin, password: password: acree2026, hash is SHA-256)
INSERT INTO users (id, username, password_hash)
VALUES ('admin-1', 'admin', 'b1ad3693dc2c92159e28f136af9609020c9d671f51a1c00b74a01a2c0c05d84f');

-- Seed Mock Products Catalog
INSERT INTO products (id, name, price, image_url, description, category) VALUES
('elden-ring', 'Elden Ring: Shadow of the Erdtree', 39.99, '/images/elden.jpg', 'An expansion featuring an all-new story set in the Land of Shadow, filled with new bosses, dungeons, and equipment.', 'Action RPG'),
('cyberpunk-2077', 'Cyberpunk 2077: Ultimate Edition', 59.99, '/images/cyberpunk.jpg', 'An open-world, action-adventure RPG set in Night City. You play as V, a mercenary outlaw fighting for survival.', 'Sci-Fi RPG'),
('hades-ii', 'Hades II', 29.99, '/images/hades2.jpg', 'Battle beyond the Underworld using dark sorcery to take on the Titan of Time in this rogue-like dungeon crawler.', 'Rogue-like RPG'),
('baldurs-gate-3', 'Baldur''s Gate 3', 59.99, '/images/bg3.jpg', 'Gather your party and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival.', 'RPG'),
('celeste', 'Celeste', 19.99, '/images/celeste.jpg', 'Help Madeline survive her inner demons on her journey to the top of Celeste Mountain, in this super-tight platformer.', 'Platformer'),
('metroid-prime', 'Metroid Prime Remastered', 39.99, '/images/metroid.jpg', 'The first-person platforming classic, fully remastered for Nintendo Switch with modern controls, visuals, and audio.', 'Action Adventure');

-- Seed Initial Pages Metadata
INSERT INTO pages (id, slug, title)
VALUES ('homepage', '/', 'Home');

-- Seed Initial Page Draft (Contains all 7 sections mapped out in JSON)
INSERT INTO page_drafts (page_id, content_json)
VALUES (
  'homepage',
  '{"id":"homepage","slug":"/","seo":{"title":"ACREE | Premium Gaming Store","description":"Welcome to ACREE, the ultimate destination for premium games, digital keys, and live tournament events.","ogImage":"/images/hero-bg.jpg"},"sections":[{"id":"promo-1","type":"promoBanner","props":{"text":"Summer Games Showcase! Save up to 50% on selected digital keys.","bgColor":"#1e1b4b","textColor":"#e0e7ff","link":"#featured-products"}},{"id":"hero-1","type":"hero","props":{"title":"Unleash Next-Gen Gaming","subtitle":"Discover handpicked masterpieces, direct digital downloads, and exclusive keys with instant email delivery.","backgroundImage":"/images/hero-bg.jpg","ctaText":"Browse Catalog","ctaLink":"#featured-products"}},{"id":"featured-1","type":"featuredProducts","props":{"title":"Featured Masterpieces","subtitle":"Highly rated, critically acclaimed games ready to play today.","productIds":["elden-ring","cyberpunk-2077","hades-ii","baldurs-gate-3"]}},{"id":"event-1","type":"eventBanner","props":{"title":"Cyber Tournament 2026","description":"Join our annual speedrunning and competitive esports tournament live stream. Register now for early bracket entry and exclusive in-game rewards.","date":"June 24, 2026","image":"/images/event-banner.jpg","ctaText":"Register Now","ctaLink":"#register"}},{"id":"testimonials-1","type":"testimonials","props":{"title":"What Our Players Say","items":[{"quote":"ACREE has the fastest key delivery I''ve ever experienced. I bought Elden Ring and was in the game in less than 2 minutes!","author":"Marcus V.","role":"Verified Buyer","avatar":"/images/avatar-marcus.jpg"},{"quote":"The customer support is incredible. I had an issue with an epic key and they resolved it in less than 5 minutes.","author":"Elena R.","role":"Community Member","avatar":"/images/avatar-elena.jpg"}]}},{"id":"cta-1","type":"cta","props":{"title":"Join the ACREE Guild","subtitle":"Sign up for our newsletter to receive weekly discount codes, tournament announcements, and developer interviews.","buttonText":"Join Newsletter","buttonLink":"#newsletter"}},{"id":"faq-1","type":"faq","props":{"title":"Frequently Asked Questions","items":[{"question":"How do I redeem my game key?","answer":"Once your payment is confirmed, the digital key is displayed immediately on the confirmation page and emailed to you. You can redeem it on Steam, Epic Games, or the respective console storefront."},{"question":"Are the keys authorized?","answer":"Yes, all game keys sold on ACREE are sourced directly from authorized publishers and distributors. We guarantee 100% genuine keys."},{"question":"What is your refund policy?","answer":"We offer a 14-day refund policy on unredeemed game keys. Once a key has been revealed or activated, it cannot be refunded."}]}}]}'
);

-- Seed Initial Published Page (Copy of draft so storefront renders initially)
INSERT INTO page_published (page_id, content_json)
VALUES (
  'homepage',
  '{"id":"homepage","slug":"/","seo":{"title":"ACREE | Premium Gaming Store","description":"Welcome to ACREE, the ultimate destination for premium games, digital keys, and live tournament events.","ogImage":"/images/hero-bg.jpg"},"sections":[{"id":"promo-1","type":"promoBanner","props":{"text":"Summer Games Showcase! Save up to 50% on selected digital keys.","bgColor":"#1e1b4b","textColor":"#e0e7ff","link":"#featured-products"}},{"id":"hero-1","type":"hero","props":{"title":"Unleash Next-Gen Gaming","subtitle":"Discover handpicked masterpieces, direct digital downloads, and exclusive keys with instant email delivery.","backgroundImage":"/images/hero-bg.jpg","ctaText":"Browse Catalog","ctaLink":"#featured-products"}},{"id":"featured-1","type":"featuredProducts","props":{"title":"Featured Masterpieces","subtitle":"Highly rated, critically acclaimed games ready to play today.","productIds":["elden-ring","cyberpunk-2077","hades-ii","baldurs-gate-3"]}},{"id":"event-1","type":"eventBanner","props":{"title":"Cyber Tournament 2026","description":"Join our annual speedrunning and competitive esports tournament live stream. Register now for early bracket entry and exclusive in-game rewards.","date":"June 24, 2026","image":"/images/event-banner.jpg","ctaText":"Register Now","ctaLink":"#register"}},{"id":"testimonials-1","type":"testimonials","props":{"title":"What Our Players Say","items":[{"quote":"ACREE has the fastest key delivery I''ve ever experienced. I bought Elden Ring and was in the game in less than 2 minutes!","author":"Marcus V.","role":"Verified Buyer","avatar":"/images/avatar-marcus.jpg"},{"quote":"The customer support is incredible. I had an issue with an epic key and they resolved it in less than 5 minutes.","author":"Elena R.","role":"Community Member","avatar":"/images/avatar-elena.jpg"}]}},{"id":"cta-1","type":"cta","props":{"title":"Join the ACREE Guild","subtitle":"Sign up for our newsletter to receive weekly discount codes, tournament announcements, and developer interviews.","buttonText":"Join Newsletter","buttonLink":"#newsletter"}},{"id":"faq-1","type":"faq","props":{"title":"Frequently Asked Questions","items":[{"question":"How do I redeem my game key?","answer":"Once your payment is confirmed, the digital key is displayed immediately on the confirmation page and emailed to you. You can redeem it on Steam, Epic Games, or the respective console storefront."},{"question":"Are the keys authorized?","answer":"Yes, all game keys sold on ACREE are sourced directly from authorized publishers and distributors. We guarantee 100% genuine keys."},{"question":"What is your refund policy?","answer":"We offer a 14-day refund policy on unredeemed game keys. Once a key has been revealed or activated, it cannot be refunded."}]}}]}'
);
